apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-minio
  labels:
    app: eorzea-minio
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: api
    - port: {{ .Values.consolePort }}
      targetPort: {{ .Values.consolePort }}
      protocol: TCP
      name: console
  selector:
    app: eorzea-minio
