apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-producer
  labels:
    app: eorzea-producer
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: eorzea-producer
  template:
    metadata:
      labels:
        app: eorzea-producer
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: producer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Release.Name }}-kafka:9092"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
