apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kafka
  labels:
    app: eorzea-kafka
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
  selector:
    app: eorzea-kafka
