# -- Eorzea Platform Umbrella Values --
secrets:
  anthropicApiKey: ""

api:
  replicaCount: 1
  image:
    tag: latest

frontend:
  replicaCount: 1
  image:
    tag: latest

kafka:
  replicaCount: 1

minio:
  persistence:
    size: 5Gi

producer:
  replicaCount: 1

airflow:
  executor: LocalExecutor
  redis:
    enabled: false
  flower:
    enabled: false
  dags:
    gitSync:
      enabled: true
      repo: "https://github.com/chris-heap/eorzea-marketplace-platform.git"
      branch: main
      subPath: "airflow/dags"
      wait: 60
  postgresql:
    image:
      tag: "latest"

